### PR TITLE
Update autodoc

### PR DESCRIPTION
**Pull request by gilesbradshaw**

### CODE REVIEW

**Comment by dtao** [comment]
What's the goal here?

**Comment by gilesbradshaw** [comment]
It was breaking my code - on Node 7 I think

**Comment by dtao** [comment]
Ha, looks like you're right.

Minor bit of feedback: a descriptive commit message could have explained what was being fixed and answered my question before I asked it. ("Update autodoc" is about as generic as it gets.)

**Comment by gilesbradshaw** [comment]
ha sorry yes - just lazy

**Pull request merged**
